
CREATE TABLE SEEK_ANALYSIS
(
  ANALYSIS_ID          CHAR(36)     NOT NULL,
  ANALYSIS_TYPE_CCD    VARCHAR(30)  NOT NULL,
  ANALYSIS_STATUS_CCD  VARCHAR(30)  NOT NULL,
  ANALYSIS_MODEL       VARCHAR(128),
  ANALYSIS_START_DT    TIMESTAMP   ,
  ANALYSIS_END_DT      TIMESTAMP   ,
  ANALYSIS_TIME        NUMERIC(10) ,
  TOTAL_DETECTED_COUNT NUMERIC(5)  ,
  CREATE_DT            TIMESTAMP    NOT NULL,
  PRIMARY KEY (ANALYSIS_ID)
);

COMMENT ON TABLE SEEK_ANALYSIS IS '분석';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_TYPE_CCD IS '분석_타입_공통코드';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_STATUS_CCD IS '분석_상태_공통코드';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_MODEL IS '분석_모델';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_START_DT IS '분석_시작_일시';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_END_DT IS '분석_종료_일시';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_TIME IS '분석_시간(ms)';

COMMENT ON COLUMN SEEK_ANALYSIS.TOTAL_DETECTED_COUNT IS '전체_검출_개수';

COMMENT ON COLUMN SEEK_ANALYSIS.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_ANALYSIS_DATABASE
(
  ANALYSIS_ID        CHAR(36)     NOT NULL,
  TARGET_INFORMATION VARCHAR(256) NOT NULL,
  ANALYSIS_CONTENT   TEXT         NOT NULL,
  PRIMARY KEY (ANALYSIS_ID)
);

COMMENT ON TABLE SEEK_ANALYSIS_DATABASE IS '분석_데이터베이스';

COMMENT ON COLUMN SEEK_ANALYSIS_DATABASE.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_ANALYSIS_DATABASE.TARGET_INFORMATION IS '대상_정보';

COMMENT ON COLUMN SEEK_ANALYSIS_DATABASE.ANALYSIS_CONTENT IS '분석_내용';

CREATE TABLE SEEK_ANALYSIS_ERROR
(
  ANALYSIS_ID       CHAR(36)   NOT NULL,
  ANALYSIS_ERROR_SN NUMERIC(5) NOT NULL,
  ANALYSIS_DATA     TEXT       NOT NULL,
  ERROR_MESSAGE     TEXT       NOT NULL,
  EXCLUSION_DT      TIMESTAMP ,
  CREATE_DT         TIMESTAMP  NOT NULL,
  PRIMARY KEY (ANALYSIS_ID, ANALYSIS_ERROR_SN)
);

COMMENT ON TABLE SEEK_ANALYSIS_ERROR IS '분석_오류';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.ANALYSIS_ERROR_SN IS '분석_오류_순번';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.ANALYSIS_DATA IS '분석_데이터';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.ERROR_MESSAGE IS '오류_메시지';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.EXCLUSION_DT IS '배제_일시';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_ANALYSIS_PROXY
(
  ANALYSIS_ID        CHAR(36)    NOT NULL,
  OPERATION_ID       VARCHAR(36) NOT NULL,
  OPERATION_TYPE_CCD VARCHAR(30) NOT NULL,
  URL                TEXT        NOT NULL,
  HEADER             TEXT        NOT NULL,
  QUERY_STRING       TEXT       ,
  BODY               TEXT       ,
  FILE_ID            CHAR(36)   ,
  PRIMARY KEY (ANALYSIS_ID)
);

COMMENT ON TABLE SEEK_ANALYSIS_PROXY IS '분석_프록시';

COMMENT ON COLUMN SEEK_ANALYSIS_PROXY.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_ANALYSIS_PROXY.OPERATION_ID IS '작업_ID';

COMMENT ON COLUMN SEEK_ANALYSIS_PROXY.OPERATION_TYPE_CCD IS '작업_유형_공통코드';

COMMENT ON COLUMN SEEK_ANALYSIS_PROXY.URL IS 'URL';

COMMENT ON COLUMN SEEK_ANALYSIS_PROXY.HEADER IS '헤더';

COMMENT ON COLUMN SEEK_ANALYSIS_PROXY.QUERY_STRING IS '쿼리_문자열';

COMMENT ON COLUMN SEEK_ANALYSIS_PROXY.BODY IS '바디';

COMMENT ON COLUMN SEEK_ANALYSIS_PROXY.FILE_ID IS '파일_ID';

CREATE TABLE SEEK_ANALYSIS_RESULT_ITEMS
(
  ANALYSIS_ID        CHAR(36)    NOT NULL,
  DETECTION_TYPE_CCD VARCHAR(30) NOT NULL,
  DETECTED_COUNT     NUMERIC(5)  NOT NULL,
  PRIMARY KEY (ANALYSIS_ID, DETECTION_TYPE_CCD)
);

COMMENT ON TABLE SEEK_ANALYSIS_RESULT_ITEMS IS '분석_결과_항목';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT_ITEMS.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT_ITEMS.DETECTION_TYPE_CCD IS '검출_타입_공통코드';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT_ITEMS.DETECTED_COUNT IS '검출_개수';

CREATE TABLE SEEK_COM_CD
(
  GROUP_CD   VARCHAR(30)  NOT NULL,
  COM_CD     VARCHAR(30)  NOT NULL,
  COM_CD_NM  VARCHAR(100) NOT NULL,
  SORT_SN    NUMERIC(5)   NOT NULL,
  USE_YN     CHAR(1)      NOT NULL,
  CREATE_DT  TIMESTAMP    NOT NULL,
  CREATE_UID CHAR(36)     NOT NULL,
  MODIFY_DT  TIMESTAMP    NOT NULL,
  MODIFY_UID CHAR(36)     NOT NULL,
  PRIMARY KEY (GROUP_CD, COM_CD)
);

COMMENT ON TABLE SEEK_COM_CD IS '공통_코드';

COMMENT ON COLUMN SEEK_COM_CD.GROUP_CD IS '그룹_코드';

COMMENT ON COLUMN SEEK_COM_CD.COM_CD IS '공통_코드';

COMMENT ON COLUMN SEEK_COM_CD.COM_CD_NM IS '공통_코드_명';

COMMENT ON COLUMN SEEK_COM_CD.SORT_SN IS '정렬_순번';

COMMENT ON COLUMN SEEK_COM_CD.USE_YN IS '사용_여부';

COMMENT ON COLUMN SEEK_COM_CD.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_COM_CD.CREATE_UID IS '생성자_식별자';

COMMENT ON COLUMN SEEK_COM_CD.MODIFY_DT IS '수정_일시';

COMMENT ON COLUMN SEEK_COM_CD.MODIFY_UID IS '수정자_식별자';

CREATE TABLE SEEK_COM_CD_GROUP
(
  GROUP_CD    VARCHAR(30) NOT NULL,
  GROUP_CD_NM VARCHAR(30) NOT NULL,
  CREATE_DT   TIMESTAMP   NOT NULL,
  CREATE_UID  CHAR(36)    NOT NULL,
  MODIFY_DT   TIMESTAMP   NOT NULL,
  MODIFY_UID  CHAR(36)    NOT NULL,
  PRIMARY KEY (GROUP_CD)
);

COMMENT ON TABLE SEEK_COM_CD_GROUP IS '공통_코드_그룹';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.GROUP_CD IS '그룹_코드';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.GROUP_CD_NM IS '그룹_코드_명';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.CREATE_UID IS '생성자_식별자';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.MODIFY_DT IS '수정_일시';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.MODIFY_UID IS '수정자_식별자';

CREATE TABLE SEEK_FILE
(
  FILE_ID     CHAR(36)    NOT NULL,
  FILE_SE_CCD VARCHAR(30) NOT NULL,
  CREATE_DT   TIMESTAMP   NOT NULL,
  DELETE_DT   TIMESTAMP   NOT NULL,
  PRIMARY KEY (FILE_ID)
);

COMMENT ON TABLE SEEK_FILE IS '파일';

COMMENT ON COLUMN SEEK_FILE.FILE_ID IS '파일_ID';

COMMENT ON COLUMN SEEK_FILE.FILE_SE_CCD IS '파일_구분_공통코드';

COMMENT ON COLUMN SEEK_FILE.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_FILE.DELETE_DT IS '삭제_일시';

CREATE TABLE SEEK_FILE_DETAIL
(
  FILE_DETAIL_ID CHAR(36)     NOT NULL,
  FILE_ID        CHAR(36)     NOT NULL,
  FILE_NAME      VARCHAR(256) NOT NULL,
  FILE_EXT       VARCHAR(30) ,
  FILE_SIZE      NUMERIC(20)  NOT NULL,
  CONTENT_TYPE   VARCHAR(128),
  SAVE_PATH      VARCHAR(512) NOT NULL,
  SAVE_NAME      VARCHAR(256) NOT NULL,
  SORT_SN        NUMERIC(5)  ,
  CREATE_DT      TIMESTAMP   ,
  DELETE_DT      TIMESTAMP   ,
  PRIMARY KEY (FILE_DETAIL_ID)
);

COMMENT ON TABLE SEEK_FILE_DETAIL IS '파일_상세';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_DETAIL_ID IS '파일_상세_ID';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_ID IS '파일_ID';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_NAME IS '파일_명';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_EXT IS '파일_확장자';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_SIZE IS '파일_크기';

COMMENT ON COLUMN SEEK_FILE_DETAIL.CONTENT_TYPE IS '콘텐츠_타입';

COMMENT ON COLUMN SEEK_FILE_DETAIL.SAVE_PATH IS '저장_경로';

COMMENT ON COLUMN SEEK_FILE_DETAIL.SAVE_NAME IS '저장_명';

COMMENT ON COLUMN SEEK_FILE_DETAIL.SORT_SN IS '정렬_순번';

COMMENT ON COLUMN SEEK_FILE_DETAIL.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_FILE_DETAIL.DELETE_DT IS '삭제_일시';

CREATE TABLE SEEK_SENSITIVE_INFORMATION
(
  SENSITIVE_INFORMATION_ID CHAR(37)    NOT NULL,
  TARGET_TEXT              TEXT        NOT NULL,
  ESCAPE_TEXT              TEXT        NOT NULL,
  HIT_COUNT                NUMERIC(5)  NOT NULL,
  SEVERITY_CCD             VARCHAR(30),
  CREATE_DT                TIMESTAMP   NOT NULL,
  MODIFY_DT                TIMESTAMP   NOT NULL,
  PRIMARY KEY (SENSITIVE_INFORMATION_ID)
);

COMMENT ON TABLE SEEK_SENSITIVE_INFORMATION IS '민감_정보';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.SENSITIVE_INFORMATION_ID IS '민감_정보_ID';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.TARGET_TEXT IS '대상_문자열';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.ESCAPE_TEXT IS '대체_문자열';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.HIT_COUNT IS '탐지_횟수';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.SEVERITY_CCD IS '심각도_공통코드';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.MODIFY_DT IS '수정_일시';

CREATE TABLE SEEK_SENSITIVE_INFORMATION_TYPES
(
  SENSITIVE_INFORMATION_ID CHAR(37)    NOT NULL,
  DETECTION_TYPE_CCD       VARCHAR(30) NOT NULL,
  PRIMARY KEY (SENSITIVE_INFORMATION_ID, DETECTION_TYPE_CCD)
);

COMMENT ON TABLE SEEK_SENSITIVE_INFORMATION_TYPES IS '민감_정보_유형';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_TYPES.SENSITIVE_INFORMATION_ID IS '민감_정보_ID';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_TYPES.DETECTION_TYPE_CCD IS '검출_타입_공통코드';

CREATE TABLE TB_ARTICLE
(
  ARTICLE_ID       CHAR(36)    NOT NULL,
  ARTICLE_TYPE_CCD VARCHAR(30) NOT NULL,
  CONTENT          TEXT       ,
  FILE_ID          CHAR(36)   ,
  CREATE_DT        TIMESTAMP   NOT NULL,
  MODIFY_DT        TIMESTAMP   NOT NULL,
  PRIMARY KEY (ARTICLE_ID)
);

COMMENT ON TABLE TB_ARTICLE IS '게시글';

COMMENT ON COLUMN TB_ARTICLE.ARTICLE_ID IS '게시글_ID';

COMMENT ON COLUMN TB_ARTICLE.ARTICLE_TYPE_CCD IS '게시글_타입_공통코드';

COMMENT ON COLUMN TB_ARTICLE.CONTENT IS '내용';

COMMENT ON COLUMN TB_ARTICLE.FILE_ID IS '파일_ID';

COMMENT ON COLUMN TB_ARTICLE.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN TB_ARTICLE.MODIFY_DT IS '수정_일시';

CREATE TABLE TB_FILE
(
  FILE_ID     CHAR(36)    NOT NULL,
  FILE_SE_CCD VARCHAR(30) NOT NULL,
  CREATE_DT   TIMESTAMP   NOT NULL,
  CREATE_UID  CHAR(36)   ,
  MODIFY_DT   TIMESTAMP   NOT NULL,
  MODIFY_UID  CHAR(36)    NOT NULL,
  DELETE_DT   TIMESTAMP  ,
  DELETE_UID  CHAR(36)   ,
  PRIMARY KEY (FILE_ID)
);

COMMENT ON TABLE TB_FILE IS '파일';

COMMENT ON COLUMN TB_FILE.FILE_ID IS '파일_ID';

COMMENT ON COLUMN TB_FILE.FILE_SE_CCD IS '파일_구분_공통코드';

COMMENT ON COLUMN TB_FILE.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN TB_FILE.CREATE_UID IS '생성자_식별자';

COMMENT ON COLUMN TB_FILE.MODIFY_DT IS '수정_일시';

COMMENT ON COLUMN TB_FILE.MODIFY_UID IS '수정자_식별자';

COMMENT ON COLUMN TB_FILE.DELETE_DT IS '삭제_일시';

COMMENT ON COLUMN TB_FILE.DELETE_UID IS '삭제자_식별자';

CREATE TABLE TB_FILE_DETAIL
(
  FILE_DETAIL_ID CHAR(36)     NOT NULL,
  FILE_ID        CHAR(36)     NOT NULL,
  FILE_NAME      VARCHAR(256) NOT NULL,
  FILE_EXT       VARCHAR(30) ,
  FILE_SIZE      NUMERIC(20)  NOT NULL,
  CONTENT_TYPE   VARCHAR(128),
  SAVE_PATH      VARCHAR(512) NOT NULL,
  SAVE_NAME      VARCHAR(256) NOT NULL,
  SORT_SN        NUMERIC(5)  ,
  CREATE_DT      TIMESTAMP    NOT NULL,
  CREATE_UID     CHAR(36)     NOT NULL,
  MODIFY_DT      TIMESTAMP    NOT NULL,
  MODIFY_UID     CHAR(36)     NOT NULL,
  DELETE_DT      TIMESTAMP   ,
  DELETE_UID     CHAR(36)    ,
  PRIMARY KEY (FILE_DETAIL_ID)
);

COMMENT ON TABLE TB_FILE_DETAIL IS '파일_상세';

COMMENT ON COLUMN TB_FILE_DETAIL.FILE_DETAIL_ID IS '파일_상세_ID';

COMMENT ON COLUMN TB_FILE_DETAIL.FILE_ID IS '파일_ID';

COMMENT ON COLUMN TB_FILE_DETAIL.FILE_NAME IS '파일_명';

COMMENT ON COLUMN TB_FILE_DETAIL.FILE_EXT IS '파일_확장자';

COMMENT ON COLUMN TB_FILE_DETAIL.FILE_SIZE IS '파일_크기';

COMMENT ON COLUMN TB_FILE_DETAIL.CONTENT_TYPE IS '콘텐츠_타입';

COMMENT ON COLUMN TB_FILE_DETAIL.SAVE_PATH IS '저장_경로';

COMMENT ON COLUMN TB_FILE_DETAIL.SAVE_NAME IS '저장_명';

COMMENT ON COLUMN TB_FILE_DETAIL.SORT_SN IS '정렬_순번';

COMMENT ON COLUMN TB_FILE_DETAIL.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN TB_FILE_DETAIL.CREATE_UID IS '생성자_식별자';

COMMENT ON COLUMN TB_FILE_DETAIL.MODIFY_DT IS '수정_일시';

COMMENT ON COLUMN TB_FILE_DETAIL.MODIFY_UID IS '수정자_식별자';

COMMENT ON COLUMN TB_FILE_DETAIL.DELETE_DT IS '삭제_일시';

COMMENT ON COLUMN TB_FILE_DETAIL.DELETE_UID IS '삭제자_식별자';

ALTER TABLE SEEK_COM_CD
  ADD CONSTRAINT FK_SEEK_COM_CD_GROUP_TO_SEEK_COM_CD
    FOREIGN KEY (GROUP_CD)
    REFERENCES SEEK_COM_CD_GROUP (GROUP_CD);

ALTER TABLE TB_FILE_DETAIL
  ADD CONSTRAINT FK_TB_FILE_TO_TB_FILE_DETAIL
    FOREIGN KEY (FILE_ID)
    REFERENCES TB_FILE (FILE_ID);

ALTER TABLE SEEK_ANALYSIS_RESULT_ITEMS
  ADD CONSTRAINT FK_SEEK_ANALYSIS_TO_SEEK_ANALYSIS_RESULT_ITEMS
    FOREIGN KEY (ANALYSIS_ID)
    REFERENCES SEEK_ANALYSIS (ANALYSIS_ID);

ALTER TABLE SEEK_SENSITIVE_INFORMATION_TYPES
  ADD CONSTRAINT FK_SEEK_SENSITIVE_INFORMATION_TYPES_01
    FOREIGN KEY (SENSITIVE_INFORMATION_ID)
    REFERENCES SEEK_SENSITIVE_INFORMATION (SENSITIVE_INFORMATION_ID);

ALTER TABLE SEEK_ANALYSIS_ERROR
  ADD CONSTRAINT FK_SEEK_ANALYSIS_TO_SEEK_ANALYSIS_ERROR
    FOREIGN KEY (ANALYSIS_ID)
    REFERENCES SEEK_ANALYSIS (ANALYSIS_ID);

ALTER TABLE SEEK_ANALYSIS_PROXY
  ADD CONSTRAINT FK_SEEK_ANALYSIS_TO_SEEK_ANALYSIS_PROXY
    FOREIGN KEY (ANALYSIS_ID)
    REFERENCES SEEK_ANALYSIS (ANALYSIS_ID);

ALTER TABLE SEEK_ANALYSIS_DATABASE
  ADD CONSTRAINT FK_SEEK_ANALYSIS_TO_SEEK_ANALYSIS_DATABASE
    FOREIGN KEY (ANALYSIS_ID)
    REFERENCES SEEK_ANALYSIS (ANALYSIS_ID);

ALTER TABLE SEEK_FILE_DETAIL
  ADD CONSTRAINT FK_SEEK_FILE_TO_SEEK_FILE_DETAIL
    FOREIGN KEY (FILE_ID)
    REFERENCES SEEK_FILE (FILE_ID);
