
CREATE TABLE SEEK_AGENT
(
  CLIENT_IP                 VARCHAR(32)  NOT NULL,
  USER_ID                   VARCHAR(36) ,
  HOST                      VARCHAR(256),
  MAC_ADDR                  VARCHAR(17) ,
  ORG_CODE                  VARCHAR(30) ,
  EVENT_DT                  TIMESTAMP   ,
  MINISPY_SYS_YN            CHAR(1)      NOT NULL,
  MSPY_USER_EXE_YN          CHAR(1)      NOT NULL,
  WFP_BLOCKER_EXE_YN        CHAR(1)      NOT NULL,
  CLICK_DOMAIN_AGENT_EXE_YN CHAR(1)      NOT NULL,
  CREATE_DT                 TIMESTAMP    NOT NULL,
  CREATE_UID                CHAR(36)     NOT NULL,
  MODIFY_DT                 TIMESTAMP    NOT NULL,
  MODIFY_UID                CHAR(36)     NOT NULL,
  PRIMARY KEY (CLIENT_IP)
);

COMMENT ON TABLE SEEK_AGENT IS 'SEEK_에이전트';

COMMENT ON COLUMN SEEK_AGENT.CLIENT_IP IS '클라이언트_IP';

COMMENT ON COLUMN SEEK_AGENT.USER_ID IS '사용자_ID';

COMMENT ON COLUMN SEEK_AGENT.HOST IS '호스트';

COMMENT ON COLUMN SEEK_AGENT.MAC_ADDR IS 'MAC__주소';

COMMENT ON COLUMN SEEK_AGENT.ORG_CODE IS '조직_코드';

COMMENT ON COLUMN SEEK_AGENT.EVENT_DT IS '이벤트_일시';

COMMENT ON COLUMN SEEK_AGENT.MINISPY_SYS_YN IS 'minispy.sys_활성화_여부';

COMMENT ON COLUMN SEEK_AGENT.MSPY_USER_EXE_YN IS 'mspyUser.exe_활성화_여부';

COMMENT ON COLUMN SEEK_AGENT.WFP_BLOCKER_EXE_YN IS 'WfpBlocker.exe_활성화_여부';

COMMENT ON COLUMN SEEK_AGENT.CLICK_DOMAIN_AGENT_EXE_YN IS 'ClickDomainAgent.exe_활성화_여부';

COMMENT ON COLUMN SEEK_AGENT.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_AGENT.CREATE_UID IS '생성자_식별자';

COMMENT ON COLUMN SEEK_AGENT.MODIFY_DT IS '수정_일시';

COMMENT ON COLUMN SEEK_AGENT.MODIFY_UID IS '수정자_식별자';

CREATE TABLE SEEK_AGENT_HEARTBEAT_HIST
(
  CLIENT_IP                 VARCHAR(32)  ,
  USER_ID                   VARCHAR(36)  ,
  HOST                      VARCHAR(256) ,
  MAC_ADDR                  VARCHAR(17)  ,
  ORG_CODE                  VARCHAR(30)  ,
  EVENT_TIME                VARCHAR(36)  ,
  COMPONENTS                VARCHAR(1024),
  EVENT_DT                  TIMESTAMP    ,
  MINISPY_SYS_YN            CHAR(1)      ,
  MSPY_USER_EXE_YN          CHAR(1)      ,
  WFP_BLOCKER_EXE_YN        CHAR(1)      ,
  CLICK_DOMAIN_AGENT_EXE_YN CHAR(1)      ,
  CREATE_DT                 TIMESTAMP     NOT NULL
);

COMMENT ON TABLE SEEK_AGENT_HEARTBEAT_HIST IS 'SEE_에이전트_상태확인_이력';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.CLIENT_IP IS '클라이언트_IP';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.USER_ID IS '사용자_ID';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.HOST IS '호스트';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.MAC_ADDR IS 'MAC__주소';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.ORG_CODE IS '조직_코드';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.EVENT_TIME IS '이벤트_시간';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.COMPONENTS IS '컴포넌트';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.EVENT_DT IS '이벤트_일시';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.MINISPY_SYS_YN IS '파일_차단_상태_여부';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.MSPY_USER_EXE_YN IS 'SSH/FTP_차단_상태_여부';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.WFP_BLOCKER_EXE_YN IS '화이트리스트_상태_여부';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.CLICK_DOMAIN_AGENT_EXE_YN IS '서명_검증_상태_여부';

COMMENT ON COLUMN SEEK_AGENT_HEARTBEAT_HIST.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_ANALYSIS
(
  ANALYSIS_ID         CHAR(36)     NOT NULL,
  ANALYSIS_MODE_CCD   VARCHAR(30)  NOT NULL,
  ANALYSIS_STATUS_CCD VARCHAR(30)  NOT NULL,
  ANALYSIS_MODEL      VARCHAR(128),
  ANALYSIS_DATA_HASH  CHAR(16)    ,
  ANALYSIS_RESULT_ID  CHAR(16)    ,
  ANALYSIS_START_DT   TIMESTAMP   ,
  ANALYSIS_END_DT     TIMESTAMP   ,
  ANALYSIS_TIME       NUMERIC(10) ,
  REQUEST_ID          VARCHAR(64) ,
  CLIENT_IP           VARCHAR(32) ,
  USER_ID             VARCHAR(36) ,
  CREATE_DT           TIMESTAMP    NOT NULL,
  MODIFY_DT           TIMESTAMP    NOT NULL,
  PRIMARY KEY (ANALYSIS_ID)
);

COMMENT ON TABLE SEEK_ANALYSIS IS '분석';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_MODE_CCD IS '분석_모드_공통코드';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_STATUS_CCD IS '분석_상태_공통코드';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_MODEL IS '분석_모델';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_DATA_HASH IS '분석_데이터_해시';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_RESULT_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_START_DT IS '분석_시작_일시';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_END_DT IS '분석_종료_일시';

COMMENT ON COLUMN SEEK_ANALYSIS.ANALYSIS_TIME IS '분석_시간(ms)';

COMMENT ON COLUMN SEEK_ANALYSIS.REQUEST_ID IS '요청_ID';

COMMENT ON COLUMN SEEK_ANALYSIS.CLIENT_IP IS '클라이언트_IP';

COMMENT ON COLUMN SEEK_ANALYSIS.USER_ID IS '사용자_ID';

COMMENT ON COLUMN SEEK_ANALYSIS.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_ANALYSIS.MODIFY_DT IS '수정_일시';

CREATE TABLE SEEK_ANALYSIS_DETECTIONS
(
  ANALYSIS_RESULT_ID CHAR(16)    NOT NULL,
  DETECTION_TYPE_CCD VARCHAR(30) NOT NULL,
  DETECTION_COUNT    NUMERIC(5)  NOT NULL,
  PRIMARY KEY (ANALYSIS_RESULT_ID, DETECTION_TYPE_CCD)
);

COMMENT ON TABLE SEEK_ANALYSIS_DETECTIONS IS '분석_검출';

COMMENT ON COLUMN SEEK_ANALYSIS_DETECTIONS.ANALYSIS_RESULT_ID IS '분석_결과_ID';

COMMENT ON COLUMN SEEK_ANALYSIS_DETECTIONS.DETECTION_TYPE_CCD IS '검출_타입_공통코드';

COMMENT ON COLUMN SEEK_ANALYSIS_DETECTIONS.DETECTION_COUNT IS '검출_개수';

CREATE TABLE SEEK_ANALYSIS_ERROR
(
  ANALYSIS_ID       CHAR(36)   NOT NULL,
  ANALYSIS_ERROR_SN NUMERIC(5) NOT NULL,
  ANALYSIS_DATA     TEXT       NOT NULL,
  ERROR_MESSAGE     TEXT       NOT NULL,
  EXCLUSION_DT      TIMESTAMP ,
  CREATE_DT         TIMESTAMP  NOT NULL,
  PRIMARY KEY (ANALYSIS_ID, ANALYSIS_ERROR_SN)
);

COMMENT ON TABLE SEEK_ANALYSIS_ERROR IS '분석_오류';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.ANALYSIS_ID IS '작업_ID';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.ANALYSIS_ERROR_SN IS '분석_오류_순번';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.ANALYSIS_DATA IS '분석_데이터';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.ERROR_MESSAGE IS '오류_메시지';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.EXCLUSION_DT IS '배제_일시';

COMMENT ON COLUMN SEEK_ANALYSIS_ERROR.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_ANALYSIS_RESULT
(
  ANALYSIS_RESULT_ID      CHAR(16)    NOT NULL,
  ANALYSIS_RAW_DATA       TEXT       ,
  ANALYZED_CONTENT        TEXT       ,
  MAX_DETECTION_TYPE_CCD  VARCHAR(30) NOT NULL,
  TOTAL_DETECTION_COUNT   NUMERIC(5)  NOT NULL,
  CREATE_DT               TIMESTAMP   NOT NULL,
  PRIMARY KEY (ANALYSIS_RESULT_ID)
);

COMMENT ON TABLE SEEK_ANALYSIS_RESULT IS '분석_결과';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT.ANALYSIS_RESULT_ID IS '분석_결과_ID (해시 값)';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT.ANALYSIS_RAW_DATA IS '분석_원본_데이터';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT.ANALYZED_CONTENT IS '분석된_내용';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT.MAX_DETECTION_TYPE_CCD  IS '최대_검출_타입_공통코드';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT.TOTAL_DETECTION_COUNT IS '전체_검출_개수';

COMMENT ON COLUMN SEEK_ANALYSIS_RESULT.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_COM_CD
(
  GROUP_CD   VARCHAR(30)  NOT NULL,
  COM_CD     VARCHAR(30)  NOT NULL,
  COM_CD_NM  VARCHAR(100) NOT NULL,
  SORT_SN    NUMERIC(5)   NOT NULL,
  USE_YN     CHAR(1)      NOT NULL,
  CREATE_DT  TIMESTAMP    NOT NULL,
  CREATE_UID CHAR(36)     NOT NULL,
  MODIFY_DT  TIMESTAMP    NOT NULL,
  MODIFY_UID CHAR(36)     NOT NULL,
  PRIMARY KEY (GROUP_CD, COM_CD)
);

COMMENT ON TABLE SEEK_COM_CD IS '공통_코드';

COMMENT ON COLUMN SEEK_COM_CD.GROUP_CD IS '그룹_코드';

COMMENT ON COLUMN SEEK_COM_CD.COM_CD IS '공통_코드';

COMMENT ON COLUMN SEEK_COM_CD.COM_CD_NM IS '공통_코드_명';

COMMENT ON COLUMN SEEK_COM_CD.SORT_SN IS '정렬_순번';

COMMENT ON COLUMN SEEK_COM_CD.USE_YN IS '사용_여부';

COMMENT ON COLUMN SEEK_COM_CD.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_COM_CD.CREATE_UID IS '생성자_식별자';

COMMENT ON COLUMN SEEK_COM_CD.MODIFY_DT IS '수정_일시';

COMMENT ON COLUMN SEEK_COM_CD.MODIFY_UID IS '수정자_식별자';

CREATE TABLE SEEK_COM_CD_GROUP
(
  GROUP_CD    VARCHAR(30) NOT NULL,
  GROUP_CD_NM VARCHAR(30) NOT NULL,
  CREATE_DT   TIMESTAMP   NOT NULL,
  CREATE_UID  CHAR(36)    NOT NULL,
  MODIFY_DT   TIMESTAMP   NOT NULL,
  MODIFY_UID  CHAR(36)    NOT NULL,
  PRIMARY KEY (GROUP_CD)
);

COMMENT ON TABLE SEEK_COM_CD_GROUP IS '공통_코드_그룹';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.GROUP_CD IS '그룹_코드';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.GROUP_CD_NM IS '그룹_코드_명';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.CREATE_UID IS '생성자_식별자';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.MODIFY_DT IS '수정_일시';

COMMENT ON COLUMN SEEK_COM_CD_GROUP.MODIFY_UID IS '수정자_식별자';

CREATE TABLE SEEK_CUSTOMER_INQUIRIES
(
  INQUIRIES_ID BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY,
  NAME         VARCHAR(64)  NOT NULL,
  EMAIL        VARCHAR(128) NOT NULL,
  SUBJECT      VARCHAR(512) NOT NULL,
  CONTENT      TEXT         NOT NULL,
  CREATE_DT    TIMESTAMP    NOT NULL,
  PRIMARY KEY (INQUIRIES_ID)
);

COMMENT ON TABLE SEEK_CUSTOMER_INQUIRIES IS '고객_문의사항';

COMMENT ON COLUMN SEEK_CUSTOMER_INQUIRIES.INQUIRIES_ID IS '문의사항_ID';

COMMENT ON COLUMN SEEK_CUSTOMER_INQUIRIES.NAME IS '이름';

COMMENT ON COLUMN SEEK_CUSTOMER_INQUIRIES.EMAIL IS '이메일';

COMMENT ON COLUMN SEEK_CUSTOMER_INQUIRIES.SUBJECT IS '제목';

COMMENT ON COLUMN SEEK_CUSTOMER_INQUIRIES.CONTENT IS '내용';

COMMENT ON COLUMN SEEK_CUSTOMER_INQUIRIES.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_DATABASE_ANALYSIS
(
  ANALYSIS_ID        CHAR(36) NOT NULL,
  TARGET_INFORMATION TEXT     NOT NULL,
  CONTENT            TEXT    ,
  PRIMARY KEY (ANALYSIS_ID)
);

COMMENT ON TABLE SEEK_DATABASE_ANALYSIS IS '데이터베이스_분석';

COMMENT ON COLUMN SEEK_DATABASE_ANALYSIS.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_DATABASE_ANALYSIS.TARGET_INFORMATION IS '대상_정보';

COMMENT ON COLUMN SEEK_DATABASE_ANALYSIS.CONTENT IS '내용';

CREATE TABLE SEEK_FILE
(
  FILE_ID        CHAR(36)     NOT NULL,
  FILE_SE_CCD    VARCHAR(30)  NOT NULL,
  FILE_NAME      VARCHAR(512),
  DOWNLOAD_COUNT NUMERIC(12) ,
  CREATE_DT      TIMESTAMP    NOT NULL,
  DELETE_DT      TIMESTAMP   ,
  PRIMARY KEY (FILE_ID)
);

COMMENT ON TABLE SEEK_FILE IS '파일';

COMMENT ON COLUMN SEEK_FILE.FILE_ID IS '파일_ID';

COMMENT ON COLUMN SEEK_FILE.FILE_SE_CCD IS '파일_구분_공통코드';

COMMENT ON COLUMN SEEK_FILE.FILE_NAME IS '파일_명';

COMMENT ON COLUMN SEEK_FILE.DOWNLOAD_COUNT IS '다운로드_수';

COMMENT ON COLUMN SEEK_FILE.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_FILE.DELETE_DT IS '삭제_일시';

CREATE TABLE SEEK_FILE_ANALYSIS
(
  ANALYSIS_ID       CHAR(36)    NOT NULL,
  DETECTION_FILE_ID CHAR(36)    NOT NULL,
  SIGNED_FILE_ID    CHAR(36)   ,
  SIGNED_FILE_HASH  VARCHAR(64),
  FILE_COUNT        NUMERIC(5) ,
  TOTAL_FILE_SIZE   NUMERIC(12),
  REQUESTER_UID     CHAR(36)    NOT NULL,
  PRIMARY KEY (ANALYSIS_ID)
);

COMMENT ON TABLE SEEK_FILE_ANALYSIS IS '파일_분석';

COMMENT ON COLUMN SEEK_FILE_ANALYSIS.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_FILE_ANALYSIS.DETECTION_FILE_ID IS '탐지_파일_ID';

COMMENT ON COLUMN SEEK_FILE_ANALYSIS.SIGNED_FILE_ID IS '서명된_파일_ID';

COMMENT ON COLUMN SEEK_FILE_ANALYSIS.SIGNED_FILE_HASH IS '서명된_파일_해시';

COMMENT ON COLUMN SEEK_FILE_ANALYSIS.FILE_COUNT IS '파일_개수';

COMMENT ON COLUMN SEEK_FILE_ANALYSIS.TOTAL_FILE_SIZE IS '전체_파일_크기';

COMMENT ON COLUMN SEEK_FILE_ANALYSIS.REQUESTER_UID IS '요청자_식별자';

CREATE TABLE SEEK_FILE_DETAIL
(
  FILE_DETAIL_ID CHAR(36)     NOT NULL,
  FILE_ID        CHAR(36)     NOT NULL,
  FILE_NAME      VARCHAR(256) NOT NULL,
  FILE_EXT       VARCHAR(30) ,
  FILE_SIZE      NUMERIC(20)  NOT NULL,
  FILE_HASH      CHAR(16)    ,
  CONTENT_TYPE   VARCHAR(128),
  SAVE_PATH      VARCHAR(512) NOT NULL,
  SAVE_NAME      VARCHAR(256) NOT NULL,
  DOWNLOAD_COUNT NUMERIC(12) ,
  SORT_SN        NUMERIC(5)  ,
  CREATE_DT      TIMESTAMP    NOT NULL,
  DELETE_DT      TIMESTAMP   ,
  PRIMARY KEY (FILE_DETAIL_ID)
);

COMMENT ON TABLE SEEK_FILE_DETAIL IS '파일_상세';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_DETAIL_ID IS '파일_상세_ID';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_ID IS '파일_ID';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_NAME IS '파일_명';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_EXT IS '파일_확장자';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_SIZE IS '파일_크기';

COMMENT ON COLUMN SEEK_FILE_DETAIL.FILE_HASH IS '파일_해시';

COMMENT ON COLUMN SEEK_FILE_DETAIL.CONTENT_TYPE IS '콘텐츠_타입';

COMMENT ON COLUMN SEEK_FILE_DETAIL.SAVE_PATH IS '저장_경로';

COMMENT ON COLUMN SEEK_FILE_DETAIL.SAVE_NAME IS '저장_명';

COMMENT ON COLUMN SEEK_FILE_DETAIL.DOWNLOAD_COUNT IS '다운로드_수';

COMMENT ON COLUMN SEEK_FILE_DETAIL.SORT_SN IS '정렬_순번';

COMMENT ON COLUMN SEEK_FILE_DETAIL.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_FILE_DETAIL.DELETE_DT IS '삭제_일시';

CREATE TABLE SEEK_FILE_OUTBOUND_HIST
(
  OUTBOUND_ID               BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY,
  OUTBOUND_STATUS_CCD       VARCHAR(30)  NOT NULL,
  OUTBOUND_CHANNEL_CCD      VARCHAR(30) ,
  OUTBOUND_REASON_CCD       VARCHAR(30) ,
  USER_ID                   VARCHAR(36) ,
  CLIENT_IP                 VARCHAR(32) ,
  ANALYSIS_ID               CHAR(36)    ,
  FILE_NM                   VARCHAR(500),
  ORG_CD                    VARCHAR(30) ,
  MAC_ADDR                  VARCHAR(23) ,
  DEST_HOST                 VARCHAR(500),
  TOTAL_FILE_COUNT          NUMERIC(5)  ,
  TOTAL_FILE_SIZE           NUMERIC(12) ,
  FILE_EXTENSION_STATUS_CCD VARCHAR(30) ,
  EVENT_DT                  TIMESTAMP   ,
  CREATE_DT                 TIMESTAMP    NOT NULL,
  PRIMARY KEY (OUTBOUND_ID)
);

COMMENT ON TABLE SEEK_FILE_OUTBOUND_HIST IS '파일_외부전송_이력';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.OUTBOUND_ID IS '외부전송_ID';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.OUTBOUND_STATUS_CCD IS '외부전송_상태_공통코드';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.OUTBOUND_CHANNEL_CCD IS '외부전송_채널_공통코드';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.OUTBOUND_REASON_CCD IS '외부전송_사유_공통코드';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.USER_ID IS '사용자_ID(발신자)';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.CLIENT_IP IS '클라이언트_IP';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.FILE_NM IS '파일_이름';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.ORG_CD IS '기관_코드';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.MAC_ADDR IS 'MAC_주소';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.DEST_HOST IS '목적지_호스트';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.TOTAL_FILE_COUNT IS '전체_파일_개수';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.TOTAL_FILE_SIZE IS '전체_파일_크기(바이트)';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.FILE_EXTENSION_STATUS_CCD IS '파일_확장자_상태_공통코드';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.EVENT_DT IS '이벤트(발생)_일시';

COMMENT ON COLUMN SEEK_FILE_OUTBOUND_HIST.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_MASK_HIST
(
  REQUEST_ID        CHAR(36)    NOT NULL,
  ANALYSIS_MODE_CCD VARCHAR(30) NOT NULL,
  USER_ID           VARCHAR(36),
  MASK_MODE_CCD     VARCHAR(30) NOT NULL,
  MASK_COUNT        NUMERIC(5)  NOT NULL,
  CREATE_DT         TIMESTAMP   NOT NULL,
  PRIMARY KEY (REQUEST_ID, ANALYSIS_MODE_CCD)
);

COMMENT ON TABLE SEEK_MASK_HIST IS '마스크_이력';

COMMENT ON COLUMN SEEK_MASK_HIST.REQUEST_ID IS '요청_ID';

COMMENT ON COLUMN SEEK_MASK_HIST.ANALYSIS_MODE_CCD IS '분석_모드_공통코드';

COMMENT ON COLUMN SEEK_MASK_HIST.USER_ID IS '사용자_ID';

COMMENT ON COLUMN SEEK_MASK_HIST.MASK_MODE_CCD IS '마스크_모드_공통코드';

COMMENT ON COLUMN SEEK_MASK_HIST.MASK_COUNT IS '마스크_개수';

COMMENT ON COLUMN SEEK_MASK_HIST.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_PROXY_ANALYSIS
(
  ANALYSIS_ID  CHAR(36)    NOT NULL,
  REQUEST_ID   CHAR(36)    NOT NULL,
  COUNTRY_CCD  VARCHAR(30) NOT NULL,
  URL          TEXT        NOT NULL,
  HEADER       TEXT        NOT NULL,
  QUERY_STRING TEXT       ,
  BODY         TEXT       ,
  FILE_ID      CHAR(36)   ,
  PRIMARY KEY (ANALYSIS_ID)
);

COMMENT ON TABLE SEEK_PROXY_ANALYSIS IS '프록시_분석';

COMMENT ON COLUMN SEEK_PROXY_ANALYSIS.ANALYSIS_ID IS '분석_ID';

COMMENT ON COLUMN SEEK_PROXY_ANALYSIS.REQUEST_ID IS '요청_ID';

COMMENT ON COLUMN SEEK_PROXY_ANALYSIS.COUNTRY_CCD IS '국가_공통코드';

COMMENT ON COLUMN SEEK_PROXY_ANALYSIS.URL IS 'URL';

COMMENT ON COLUMN SEEK_PROXY_ANALYSIS.HEADER IS '헤더';

COMMENT ON COLUMN SEEK_PROXY_ANALYSIS.QUERY_STRING IS '쿼리_문자열';

COMMENT ON COLUMN SEEK_PROXY_ANALYSIS.BODY IS '바디';

COMMENT ON COLUMN SEEK_PROXY_ANALYSIS.FILE_ID IS '파일_ID';

CREATE TABLE SEEK_SENSITIVE_INFORMATION
(
  SENSITIVE_INFORMATION_ID CHAR(21)    NOT NULL,
  TARGET_TEXT              TEXT        NOT NULL,
  ESCAPE_TEXT              TEXT        NOT NULL,
  HIT_COUNT                NUMERIC(5)  NOT NULL,
  SEVERITY_CCD             VARCHAR(30),
  CREATE_DT                TIMESTAMP   NOT NULL,
  MODIFY_DT                TIMESTAMP   NOT NULL,
  PRIMARY KEY (SENSITIVE_INFORMATION_ID)
);

COMMENT ON TABLE SEEK_SENSITIVE_INFORMATION IS '민감_정보';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.SENSITIVE_INFORMATION_ID IS '민감_정보_ID (해시 값)';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.TARGET_TEXT IS '대상_문자열';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.ESCAPE_TEXT IS '대체_문자열';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.HIT_COUNT IS '탐지_횟수';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.SEVERITY_CCD IS '심각도_공통코드';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION.MODIFY_DT IS '수정_일시';

CREATE TABLE SEEK_SENSITIVE_INFORMATION_MAPPING
(
  ANALYSIS_RESULT_ID       CHAR(16) NOT NULL,
  SENSITIVE_INFORMATION_ID CHAR(21) NOT NULL,
  PRIMARY KEY (ANALYSIS_RESULT_ID, SENSITIVE_INFORMATION_ID)
);

COMMENT ON TABLE SEEK_SENSITIVE_INFORMATION_MAPPING IS '민감_정보_매핑';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_MAPPING.ANALYSIS_RESULT_ID IS '분석_결과_ID (해시 값)';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_MAPPING.SENSITIVE_INFORMATION_ID IS '민감_정보_ID (해시 값)';

CREATE TABLE SEEK_SENSITIVE_INFORMATION_TYPES
(
  SENSITIVE_INFORMATION_ID CHAR(21)    NOT NULL,
  DETECTION_TYPE_CCD       VARCHAR(30) NOT NULL,
  PRIMARY KEY (SENSITIVE_INFORMATION_ID, DETECTION_TYPE_CCD)
);

COMMENT ON TABLE SEEK_SENSITIVE_INFORMATION_TYPES IS '민감_정보_유형';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_TYPES.SENSITIVE_INFORMATION_ID IS '민감_정보_ID';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_TYPES.DETECTION_TYPE_CCD IS '검출_타입_공통코드';

CREATE TABLE SEEK_SENSITIVE_INFORMATION_UNMASK_HIST
(
  REQUEST_ID                  VARCHAR(64) NOT NULL,
  CLIENT_IP                   VARCHAR(32),
  USER_ID                     VARCHAR(36),
  SENSITIVE_INFORMATION_COUNT NUMERIC(12) NOT NULL,
  CREATE_DT                   TIMESTAMP   NOT NULL,
  PRIMARY KEY (REQUEST_ID)
);

COMMENT ON TABLE SEEK_SENSITIVE_INFORMATION_UNMASK_HIST IS '민감_정보_언마스크_이력';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_UNMASK_HIST.REQUEST_ID IS '요청_ID';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_UNMASK_HIST.CLIENT_IP IS '클라이언트_IP';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_UNMASK_HIST.USER_ID IS '사용자_ID';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_UNMASK_HIST.SENSITIVE_INFORMATION_COUNT IS '민감_정보_개수';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_UNMASK_HIST.CREATE_DT IS '생성_일시';

CREATE TABLE SEEK_SENSITIVE_INFORMATION_UNMASK_INFO
(
  REQUEST_ID               VARCHAR(64) NOT NULL,
  SENSITIVE_INFORMATION_ID CHAR(21)    NOT NULL,
  PRIMARY KEY (REQUEST_ID, SENSITIVE_INFORMATION_ID)
);

COMMENT ON TABLE SEEK_SENSITIVE_INFORMATION_UNMASK_INFO IS '민감_정보_언마스크_정보';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_UNMASK_INFO.REQUEST_ID IS '요청_ID';

COMMENT ON COLUMN SEEK_SENSITIVE_INFORMATION_UNMASK_INFO.SENSITIVE_INFORMATION_ID IS '민감_정보_ID (해시 값)';

CREATE TABLE SEEK_SERVICE_WORKER_SUBSCRIPTIONS
(
  USER_ID         VARCHAR(32)  NOT NULL,
  ENDPOINT        VARCHAR(500) NOT NULL,
  KEYS_P256DH     VARCHAR(255) NOT NULL,
  KEYS_AUTH       VARCHAR(255) NOT NULL,
  EXPIRATION_DATE DATE        ,
  CREATE_DT       TIMESTAMP    NOT NULL,
  MODIFY_DT       TIMESTAMP    NOT NULL,
  PRIMARY KEY (USER_ID, ENDPOINT)
);

COMMENT ON TABLE SEEK_SERVICE_WORKER_SUBSCRIPTIONS IS '서비스_워커_구독';

COMMENT ON COLUMN SEEK_SERVICE_WORKER_SUBSCRIPTIONS.USER_ID IS '사용자_ID';

COMMENT ON COLUMN SEEK_SERVICE_WORKER_SUBSCRIPTIONS.ENDPOINT IS '엔드포인트';

COMMENT ON COLUMN SEEK_SERVICE_WORKER_SUBSCRIPTIONS.KEYS_P256DH IS '키_P256DH';

COMMENT ON COLUMN SEEK_SERVICE_WORKER_SUBSCRIPTIONS.KEYS_AUTH IS '키_인증';

COMMENT ON COLUMN SEEK_SERVICE_WORKER_SUBSCRIPTIONS.EXPIRATION_DATE IS '구독_만료일';

COMMENT ON COLUMN SEEK_SERVICE_WORKER_SUBSCRIPTIONS.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_SERVICE_WORKER_SUBSCRIPTIONS.MODIFY_DT IS '수정_일시';

CREATE TABLE SEEK_USER
(
  USER_UID   CHAR(36)     NOT NULL,
  USER_ID    VARCHAR(36)  NOT NULL,
  PASSWORD   VARCHAR(256) NOT NULL,
  NAME       VARCHAR(36)  NOT NULL,
  USE_YN     CHAR(1)      NOT NULL,
  CREATE_DT  TIMESTAMP    NOT NULL,
  CREATE_UID CHAR(36)     NOT NULL,
  MODIFY_DT  TIMESTAMP    NOT NULL,
  MODIFY_UID CHAR(36)     NOT NULL,
  DELETE_DT  TIMESTAMP   ,
  DELETE_UID CHAR(36)    ,
  PRIMARY KEY (USER_UID)
);

COMMENT ON TABLE SEEK_USER IS '사용자';

COMMENT ON COLUMN SEEK_USER.USER_UID IS '사용자_식별자';

COMMENT ON COLUMN SEEK_USER.USER_ID IS '사용자_ID';

COMMENT ON COLUMN SEEK_USER.PASSWORD IS '비밀번호';

COMMENT ON COLUMN SEEK_USER.NAME IS '이름';

COMMENT ON COLUMN SEEK_USER.USE_YN IS '사용_여부';

COMMENT ON COLUMN SEEK_USER.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN SEEK_USER.CREATE_UID IS '생성자_식별자';

COMMENT ON COLUMN SEEK_USER.MODIFY_DT IS '수정_일시';

COMMENT ON COLUMN SEEK_USER.MODIFY_UID IS '수정자_식별자';

COMMENT ON COLUMN SEEK_USER.DELETE_DT IS '삭제_ 일시';

COMMENT ON COLUMN SEEK_USER.DELETE_UID IS '삭제자_식별자';

CREATE TABLE TB_ARTICLE
(
  ARTICLE_ID       CHAR(36)    NOT NULL,
  ARTICLE_TYPE_CCD VARCHAR(30) NOT NULL,
  CONTENT          TEXT       ,
  FILE_ID          CHAR(36)   ,
  CREATE_DT        TIMESTAMP   NOT NULL,
  MODIFY_DT        TIMESTAMP   NOT NULL,
  PRIMARY KEY (ARTICLE_ID)
);

COMMENT ON TABLE TB_ARTICLE IS '게시글';

COMMENT ON COLUMN TB_ARTICLE.ARTICLE_ID IS '게시글_ID';

COMMENT ON COLUMN TB_ARTICLE.ARTICLE_TYPE_CCD IS '게시글_타입_공통코드';

COMMENT ON COLUMN TB_ARTICLE.CONTENT IS '내용';

COMMENT ON COLUMN TB_ARTICLE.FILE_ID IS '파일_ID';

COMMENT ON COLUMN TB_ARTICLE.CREATE_DT IS '생성_일시';

COMMENT ON COLUMN TB_ARTICLE.MODIFY_DT IS '수정_일시';

ALTER TABLE SEEK_COM_CD
  ADD CONSTRAINT FK_SEEK_COM_CD_GROUP_TO_SEEK_COM_CD
    FOREIGN KEY (GROUP_CD)
    REFERENCES SEEK_COM_CD_GROUP (GROUP_CD);

ALTER TABLE SEEK_ANALYSIS_DETECTIONS
  ADD CONSTRAINT FK_SEEK_ANALYSIS_RESULT_TO_SEEK_ANALYSIS_DETECTIONS
    FOREIGN KEY (ANALYSIS_RESULT_ID)
    REFERENCES SEEK_ANALYSIS_RESULT (ANALYSIS_RESULT_ID);

ALTER TABLE SEEK_SENSITIVE_INFORMATION_TYPES
  ADD CONSTRAINT FK_SEEK_SENSITIVE_INFORMATION_TO_SEEK_SENSITIVE_INFORMATION_TYPES
    FOREIGN KEY (SENSITIVE_INFORMATION_ID)
    REFERENCES SEEK_SENSITIVE_INFORMATION (SENSITIVE_INFORMATION_ID);

ALTER TABLE SEEK_FILE_DETAIL
  ADD CONSTRAINT FK_SEEK_FILE_TO_SEEK_FILE_DETAIL
    FOREIGN KEY (FILE_ID)
    REFERENCES SEEK_FILE (FILE_ID);

ALTER TABLE SEEK_PROXY_ANALYSIS
  ADD CONSTRAINT FK_SEEK_ANALYSIS_TO_SEEK_PROXY_ANALYSIS
    FOREIGN KEY (ANALYSIS_ID)
    REFERENCES SEEK_ANALYSIS (ANALYSIS_ID);

ALTER TABLE SEEK_DATABASE_ANALYSIS
  ADD CONSTRAINT FK_SEEK_ANALYSIS_TO_SEEK_DATABASE_ANALYSIS
    FOREIGN KEY (ANALYSIS_ID)
    REFERENCES SEEK_ANALYSIS (ANALYSIS_ID);

ALTER TABLE SEEK_ANALYSIS
  ADD CONSTRAINT FK_SEEK_ANALYSIS_RESULT_TO_SEEK_ANALYSIS
    FOREIGN KEY (ANALYSIS_RESULT_ID)
    REFERENCES SEEK_ANALYSIS_RESULT (ANALYSIS_RESULT_ID);

ALTER TABLE SEEK_ANALYSIS_ERROR
  ADD CONSTRAINT FK_SEEK_ANALYSIS_TO_SEEK_ANALYSIS_ERROR
    FOREIGN KEY (ANALYSIS_ID)
    REFERENCES SEEK_ANALYSIS (ANALYSIS_ID);

ALTER TABLE SEEK_SENSITIVE_INFORMATION_MAPPING
  ADD CONSTRAINT FK_SEEK_ANALYSIS_RESULT_TO_SEEK_SENSITIVE_INFORMATION_MAPPING
    FOREIGN KEY (ANALYSIS_RESULT_ID)
    REFERENCES SEEK_ANALYSIS_RESULT (ANALYSIS_RESULT_ID);

ALTER TABLE SEEK_SENSITIVE_INFORMATION_MAPPING
  ADD CONSTRAINT FK_SEEK_SENSITIVE_INFORMATION_TO_SEEK_SENSITIVE_INFORMATION_MAPPING
    FOREIGN KEY (SENSITIVE_INFORMATION_ID)
    REFERENCES SEEK_SENSITIVE_INFORMATION (SENSITIVE_INFORMATION_ID);

ALTER TABLE SEEK_FILE_ANALYSIS
  ADD CONSTRAINT FK_SEEK_ANALYSIS_TO_SEEK_FILE_ANALYSIS
    FOREIGN KEY (ANALYSIS_ID)
    REFERENCES SEEK_ANALYSIS (ANALYSIS_ID);

ALTER TABLE SEEK_SENSITIVE_INFORMATION_UNMASK_INFO
  ADD CONSTRAINT FK_SEEK_SENSITIVE_INFORMATION_UNMASK_HIST_TO_SEEK_SENSITIVE_INFORMATION_UNMASK_INFO
    FOREIGN KEY (REQUEST_ID)
    REFERENCES SEEK_SENSITIVE_INFORMATION_UNMASK_HIST (REQUEST_ID);

CREATE UNIQUE INDEX UK_USER1
  ON SEEK_USER (USER_ID ASC);
