CREATE TRIGGER TRIGGER_ARTICLE_CONTENT
    BEFORE INSERT OR UPDATE ON TB_ARTICLE
    FOR EACH ROW
EXECUTE FUNCTION FN_PREPARE_TEXT_CONTENT_FOR_ANALYSIS('tb_article', 'content', 'article_id', 'article_type_ccd');