#
# -Dspring.profiles.active=0_DEVELOP,s2
#

logging.file.path: ${user.home}/Workspaces/SEEK/_deploy/gw.placelink.biz/opt/seek/var/logs

# 시스템 속성의 "pid.file.path", "state.file.path" 경로를 배포용 모듈(경로) 하위로 설정하려면 VM 옵션에 아래의 내용을 추가한다.
# -Dpid.file.path=C:/Users/eseun/Workspaces/SEEK/_deploy/gw.placelink.biz/opt/seek/var/run
# -Dstate.file.path=C:/Users/eseun/Workspaces/SEEK/_deploy/gw.placelink.biz/opt/seek/var/state

spring:
  thymeleaf:
    prefix: file:c:/Users/eseun/Workspaces/SEEK/seek-prototype/src/main/resources/templates/
    cache: false # 개발 환경에서는 Thymeleaf 템플릿 엔진의 캐싱을 비활성화한다.

# 파일 관리자 구현체 이름
file.manager.impl.name: sftpFileManagerImpl

sftp:
  private-key-path: ${user.home}/OneDrive/.ssh/SEEK/placelink_key
