analysis:
  server:
    url: http://43.200.240.163:8000 # 분석기 서버 URL
  model-name: llama3_8b_seek_common_model
  file-signed-server:
    url: http://43.200.240.163:8090 # 파일 서명 URL
  schedule:
    enabled: true
    request:
      maxcnt: 2
  excluded-paths: /console/,/public/login,/login,/api/public/login,/api/check/login,/api/check/login,/public/js/,/public/css/,/public/images/,/public/ico/,/favicon.ico
encryption:
  password: PL408@fnw96

# 파일 관리자 구현체 이름
file.manager.impl.name: fileManagerImpl
